global:
  imageRegistry: harbor.kkamji.net
  imagePullSecrets:
    - name: harbor-credentials
fullnameOverride: image-converter
backend:
  image:
    repository: image-converter/backend
    tag: "20250628-645923"
    pullPolicy: Always
  replicaCount: 2
  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000
  resources: {}
  env:
    - name: PYTHONPATH
      value: "/app"
  healthcheck:
    enabled: true
    path: /health
    initialDelaySeconds: 30
    periodSeconds: 10
frontend:
  image:
    repository: image-converter/frontend
    tag: "20250628-645923"
    pullPolicy: Always
  replicaCount: 2
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
  resources: {}
  env:
    - name: REACT_APP_API_URL
      value: "/api"
    - name: REACT_APP_BACKEND_ENDPOINT
      value: "http://image-converter-backend:8000"
    - name: BACKEND_ENDPOINT
      value: "http://image-converter-backend:8000"
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/target: 121.130.214.237
  hosts:
    - host: image-converter.kkamji.net
      paths:
        - path: /
          pathType: Prefix
          service: frontend
        - path: /api
          pathType: Prefix
          service: backend
  tls:
    - secretName: image-converter-tls
      hosts:
        - image-converter.kkamji.net
autoscaling:
  backend:
    enabled: true
    minReplicas: 2
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80
  frontend:
    enabled: true
    minReplicas: 2
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70
podDisruptionBudget:
  enabled: true
  minAvailable: 1
nodeSelector: {}
tolerations: []
affinity: {}
