apiVersion: v1
kind: Service
metadata:
  name: {{ include "image-converter.fullname" . }}-backend
  labels:
    {{- include "image-converter.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "image-converter.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
