apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "image-converter.fullname" . }}-backend
  labels:
    {{- include "image-converter.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "image-converter.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "image-converter.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: backend
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.targetPort }}
              protocol: TCP
          {{- if .Values.backend.healthcheck.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.backend.healthcheck.path }}
              port: http
            initialDelaySeconds: {{ .Values.backend.healthcheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.healthcheck.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.backend.healthcheck.path }}
              port: http
            initialDelaySeconds: {{ .Values.backend.healthcheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.healthcheck.periodSeconds }}
          {{- end }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          env:
            {{- toYaml .Values.backend.env | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
