name: Pull Request Pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./frontend/package.json

      - name: Install uv
        run: pip install uv

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/uv
            backend/.venv
          key: ${{ runner.os }}-uv-${{ hashFiles('backend/pyproject.toml') }}

      - name: Create virtual environment and install backend dependencies
        working-directory: backend
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -e ".[dev]"

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Run backend tests
        working-directory: backend
        run: |
          source .venv/bin/activate
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest

      - name: Run frontend tests
        working-directory: frontend
        run: |
          npm test -- --coverage --watchAll=false

      - name: Run backend linting
        working-directory: backend
        run: |
          source .venv/bin/activate
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          black --check .
          isort --check-only .

      - name: Run frontend linting
        working-directory: frontend
        run: |
          npm run lint
          npm run format:check
