name: Pull Request Pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [backend, frontend]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        if: matrix.component == 'backend'
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Set up Node.js 20
        if: matrix.component == 'frontend'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./frontend/package.json

      - name: Install uv
        if: matrix.component == 'backend'
        run: pip install uv

      - name: Cache Python dependencies
        if: matrix.component == 'backend'
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/uv
            backend/.venv
          key: ${{ runner.os }}-uv-${{ hashFiles('backend/pyproject.toml') }}

      - name: Install backend dependencies
        if: matrix.component == 'backend'
        working-directory: backend
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -e ".[dev]"

      - name: Install frontend dependencies
        if: matrix.component == 'frontend'
        working-directory: frontend
        run: npm ci

      - name: Run backend tests and lint
        if: matrix.component == 'backend'
        working-directory: backend
        run: |
          source .venv/bin/activate
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest
          black --check .
          isort --check-only .

      - name: Run frontend tests and lint
        if: matrix.component == 'frontend'
        working-directory: frontend
        run: |
          npm run test:ci
          npm run lint
          npm run format:check
